const REGISTER = {
  REGISTER_INITLIZATION: "REGISTER_INITLIZATION",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERORR: "REGISTER_ERORR",
};

const LOGIN = {
  LOGIN_INITLIZATION: "LOGIN_INITLIZATION",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERORR: "LOGIN_ERORR",
};
const LOGOUT = {
  LOGOUT_INITLIZATION: "LOGOUT_INITLIZATION",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERORR: "LOGOUT_ERORR",
};
const FORGOT_PASSWORD = {
  FORGOT_PASSWORD_INITLIZATION: "FORGOT_PASSWORD_INITLIZATION",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERORR: "FORGOT_PASSWORD_ERORR",
};
const VERIFY_OTP_ACTION = {
  VERIFY_OTP_ACTION_INITLIZATION: "VERIFY_OTP_ACTION_INITLIZATION",
  VERIFY_OTP_ACTION_SUCCESS: "VERIFY_OTP_ACTION_SUCCESS",
  VERIFY_OTP_ACTION_ERORR: "VERIFY_OTP_ACTION_ERORR",
};

const GET_PROFILE = {
  GET_PROFILE_INITLIZATION: "GET_PROFILE_INITLIZATION",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_ERORR: "GET_PROFILE_ERORR",
  UPDATE_USER_FORM_DATA: "UPDATE_USER_FORM_DATA",
};
const GET_PRODUCT_LIST = {
  GET_PRODUCT_LIST_INITLIZATION: "GET_PRODUCT_LIST_INITLIZATION",
  GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_ERORR: "GET_PRODUCT_LIST_ERORR",
};
const CREATE_PRODUCT_ACTION = {
  CREATE_PRODUCT_ACTION_INITLIZATION: "CREATE_PRODUCT_ACTION_INITLIZATION",
  CREATE_PRODUCT_ACTION_SUCCESS: "CREATE_PRODUCT_ACTION_SUCCESS",
  CREATE_PRODUCT_ACTION_ERORR: "CREATE_PRODUCT_ACTION_ERORR",
};
const GET_PLAN_LIST = {
  GET_PLAN_LIST_INITLIZATION: "GET_PLAN_LIST_INITLIZATION",
  GET_PLAN_LIST_SUCCESS: "GET_PLAN_LIST_SUCCESS",
  GET_PLAN_LIST_ERORR: "GET_PLAN_LIST_ERORR",
  FLUSH_PLANS: "FLUSH_PLANS",
};
const CREATE_PLAN_ACTION = {
  CREATE_PLAN_ACTION_INITLIZATION: "CREATE_PLAN_ACTION_INITLIZATION",
  CREATE_PLAN_ACTION_SUCCESS: "CREATE_PLAN_ACTION_SUCCESS",
  CREATE_PLAN_ACTION_ERORR: "CREATE_PLAN_ACTION_ERORR",
};
const GET_COUPON_LIST = {
  GET_COUPON_LIST_INITLIZATION: "GET_COUPON_LIST_INITLIZATION",
  GET_COUPON_LIST_SUCCESS: "GET_COUPON_LIST_SUCCESS",
  GET_COUPON_LIST_ERORR: "GET_COUPON_LIST_ERORR",
  FLUSH_COUPONS: "FLUSH_COUPONS",
};
const CREATE_COUPON_ACTION = {
  CREATE_COUPON_ACTION_INITLIZATION: "CREATE_COUPON_ACTION_INITLIZATION",
  CREATE_COUPON_ACTION_SUCCESS: "CREATE_COUPON_ACTION_SUCCESS",
  CREATE_COUPON_ACTION_ERORR: "CREATE_COUPON_ACTION_ERORR",
};
const RESET_PASSWORD = {
  RESET_PASSWORD_INITLIZATION: "RESET_PASSWORD_INITLIZATION",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERORR: "RESET_PASSWORD_ERORR",
};


const GET_COMAPNY_LIST = {
  GET_COMAPNY_LIST_INITLIZATION: "GET_COMAPNY_LIST_INITLIZATION",
  GET_COMAPNY_LIST_SUCCESS: "GET_COMAPNY_LIST_SUCCESS",
  GET_COMAPNY_LIST_ERORR: "GET_COMAPNY_LIST_ERORR",
  FLUSH_COMPANIES: "FLUSH_COMPANIES",
};
export {
  REGISTER,
  LOGIN,
  FORGOT_PASSWORD,
  LOGOUT,
  VERIFY_OTP_ACTION,
  GET_PROFILE,
  GET_PRODUCT_LIST,
  CREATE_PRODUCT_ACTION,
  GET_PLAN_LIST,
  CREATE_PLAN_ACTION,
  GET_COUPON_LIST,
  CREATE_COUPON_ACTION,
  RESET_PASSWORD, GET_COMAPNY_LIST
};
